{{- if .Values.database.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "database.externalSecretName is required." .Values.database.externalSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petclinic-secrets.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ required "secretStoreName is required." .Values.secretStoreName }}
    kind: {{ .Values.secretStoreKind }}
  target:
    name: {{ required "database.targetSecretName is required." .Values.database.targetSecretName }}
    creationPolicy: {{ .Values.database.creationPolicy }}
  data:
    {{- range .Values.database.data }}
    - secretKey: {{ required "database.data[].secretKey is required." .secretKey }}
      remoteRef:
        key: {{ required "database.remoteSecretName is required." $.Values.database.remoteSecretName }}
        property: {{ required "database.data[].property is required." .property }}
    {{- end }}
{{- end }}