{{- if .Values.openai.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ required "openai.externalSecretName is required." .Values.openai.externalSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "petclinic-secrets.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ required "secretStoreName is required." .Values.secretStoreName }}
    kind: {{ .Values.secretStoreKind }}
  target:
    name: {{ required "openai.targetSecretName is required." .Values.openai.targetSecretName }}
    creationPolicy: {{ .Values.openai.creationPolicy }}
  data:
    {{- range .Values.openai.data }}
    - secretKey: {{ required "openai.data[].secretKey is required." .secretKey }}
      remoteRef:
        key: {{ required "openai.remoteSecretName is required." $.Values.openai.remoteSecretName }}
        property: {{ required "openai.data[].property is required." .property }}
    {{- end }}
{{- end }}