apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config-server-dev.yaml
  - discovery-server-dev.yaml
  - customers-service-dev.yaml
  - vets-service-dev.yaml
  - visits-service-dev.yaml
  - genai-service-dev.yaml
  - api-gateway-dev.yaml
  - admin-server-dev.yaml